# Wave v1.4 Config.

infoFormat: 0 # Формат вывода информации. 0 или 1

botsCount: 6 # Сколько ботов должно зайти на 1 сервер за раз.
joinDelay: 25 # Задержка отправки ботов на сервер (мс).

randomNicks: true # Использовать ли рандомные ники?
randomNicksLength: 8 # Длина рандомного ника.

randomPasswords: true # Использовать ли рандомные пароли?
randomPasswordsLength: 6 # Длина рандомного пароля.

doubleJoin: false # Будут ли боты перезаходить 2 раз если их кикнуло?
antiBotFilter: true # Удалять ли из списка серверов сервера с BotFilter?

testMode: false # Тестовый режим, позволяет отправлять всех ботов на один сервер.
testModeIp: "127.0.0.1:25565" # Ип тестового режима.

autoRestart: true # Включить ли авто рестарт? (очень рекомендую, но работает только на виндовс)
autoRestartDelay: 8 # Через сколько минут произойдёт рестарт. Для наилучшей эффективности ставьте не больше 10.

move: false # Будут ли боты ходить?

commands: # Что бот будет писать в чат. У wait есть только s (секунды), ms (миллисекунды)
  - "wait 5s"
  - "Hello, I'm bot"
  - "/minecraft:me Hello, I'm bot"